stages:
  - deploy

deploy_staging:
  stage: deploy
  tags: 
  - gitlab-org
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/eatngo.git
    - git push -f heroku HEAD:master
    - echo "Deployed to staging server"
  only:
    - feature/EATNGO-CI
