stages:
  - init
  - deploy

init:
  stage: init
  script:
    - npm cache clean
    - rm -rf node-modules
    - npm install

deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/eatngo.git
    - git push -f heroku master
    - echo "Deployed to staging server"
  environment:
  only:
    - feature/EATNGO-CI

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/eatngoprod.git
    - git push -f heroku master
    - echo "Deployed to production server"
  environment:
  when: manual
  only:
    - feature/EATNGO-CI
